### PR TITLE
examples/straight-el/early-init.el: update straight.el bootstrap code (bootstrap-version 7)

### PR DESCRIPTION
**Pull request by jf**

### CODE REVIEW

**Review by jeffbowman — APPROVED** [review]
LGTM, but I don't use `straight`

**Comment by jf** [comment]
sure. Unless crafted-emacs need different bootstrap code, this is basically the code straight from https://github.com/radian-software/straight.el#getting-started

**Comment by jeffbowman** [comment]
Crafted Emacs doesn't need anything additional, I was just pulling it into a virtual machine for testing purposes... and because I've been playing with `git worktree` just for things like this :-)  (game changer... wish I'd known about that sooner).  Anyway, seems to work just fine (as expected), but I like to include the other maintainers on reviews.  We're human and we miss stuff sometimes, but hopefully _one of us_ will catch most things, right! :grin:  

Appreciate your contributions!!!

**Comment by jf** [comment]
> Crafted Emacs doesn't need anything additional, I was just pulling it into a virtual machine for testing purposes... and because I've been playing with `git worktree` just for things like this :-) (game changer... wish I'd known about that sooner). Anyway, seems to work just fine (as expected), but I like to include the other maintainers on reviews. We're human and we miss stuff sometimes, but hopefully _one of us_ will catch most things, right! 😁
> 

sure.

> Appreciate your contributions!!!

and I appreciate you guys' work on crafted-emacs! at the risk of repeating myself: https://github.com/SystemCrafters/crafted-emacs/pull/419#issuecomment-2156296848

**Review by sthesing — APPROVED** [review]
I don't use straight, either. But it looks correct and runs without error when I spin up a fresh Emacs with it.

So, fine by me. Thanks!

**Review by jvdydev — APPROVED** [review]

**Pull request merged**
