### PR TITLE
Fix crafted-osx-config

### PR DESCRIPTION
**Pull request by jf**
attempts a fix at #415

### CODE REVIEW

**Comment by jeffbowman** [comment]
I looked at this, it seems reasonable, I'd like @jvdydev and/or @sthesing to also review.

**Comment by jvdydev** [comment]
Looks good!

(just a general thought)
I wonder if we can drop the `(interactive)` on `crafted-osx-transparent-titlebar` as it's probably more of a configuration-time change? (also there is no way to reverse it)

**Review by jvdydev — APPROVED** [review]

**Comment by jf** [comment]
> (just a general thought) I wonder if we can drop the `(interactive)` on `crafted-osx-transparent-titlebar` as it's probably more of a configuration-time change? (also there is no way to reverse it)

thank you for bringing that up! I've been wondering if that's even needed myself. From the help for `interactive`, Emacs says `Specify a way of parsing arguments for interactive use of a function.`. Sorry, newbie question, but what would interactive use of `crafted-osx-transparent-titlebar` look like? Would anybody use it that way?

**Review by sthesing — APPROVED** [review]
Looks good to me.
Thanks for preparing this.

**Comment by jvdydev** [comment]
> > (just a general thought) I wonder if we can drop the `(interactive)` on `crafted-osx-transparent-titlebar` as it's probably more of a configuration-time change? (also there is no way to reverse it)
> 
> thank you for bringing that up! I've been wondering if that's even needed myself. From the help for `interactive`, Emacs says `Specify a way of parsing arguments for interactive use of a function.`. Sorry, newbie question, but what would interactive use of `crafted-osx-transparent-titlebar` look like? Would anybody use it that way?

Oh, sorry, forgot to explain. Marking a function `(interactive)` essentially means it's executable using `M-x the-function`. :smile:

**Pull request merged**
