### PR TITLE
getting-started-guide.org: fix errors in info section 4.5.1 (and 4.7)

### PR DESCRIPTION
**Pull request by jf**
as per description. Diff should be self-explanatory.

### CODE REVIEW

**Comment by jf** [comment]
FYI I added another fix, this time to 4.7, instead of creating another PR.

**Review by jeffbowman — APPROVED** [review]
LGTM

**Comment by jf** [comment]
going through the info, btw, it hit me when I read 4.6 ("To save or not to save customizations") the effort, and the thought, that you guys have put into this (and that's a big part of my motivation for why I decided to go ahead and put in the effort for yet another PR). Thank you!

**Review by jvdydev — APPROVED** [review]
Looks good, thank you for catching those :smile:

**Review by sthesing — APPROVED** [review]
Good catch. Thanks!

**Comment by jf** [comment]
Sure. Just as a reminder, I think the info file needs to be regenerated?

**Comment by sthesing** [comment]
You're right. Did that. Thanks

**Pull request merged**
